In [1]:
import torch

In [3]:
# 1-dim
a = torch.rand(5)
a

tensor([0.2729, 0.8272, 0.7373, 0.6904, 0.9653])

In [4]:
max_, indices = torch.max(a, dim=0)

print(max_, indices)

tensor(0.9653) tensor(4)


In [5]:
a[indices]

tensor(0.9653)

In [ ]:
# 2-dim

In [22]:
a = torch.rand((2, 4))
a

tensor([[0.5559, 0.4322, 0.3503, 0.6921],
        [0.4734, 0.6359, 0.0196, 0.3280]])

In [23]:
row_max, indices = torch.max(a, dim=0)

row_max, indices

(tensor([0.5559, 0.6359, 0.3503, 0.6921]), tensor([0, 1, 0, 0]))

In [24]:
indices

tensor([0, 1, 0, 0])

In [43]:
a[[[0], [1]]]

tensor([0.4322])

In [46]:
indices = torch.argmax(a, dim=0)
indices

tensor([0, 1, 0, 0])

In [51]:
a[indices, torch.arange(a.size(1))]

tensor([0.5559, 0.6359, 0.3503, 0.6921])

In [53]:
torch.arange(a.size(1))

tensor([0, 1, 2, 3])

In [64]:
# 3 dim
a = torch.rand((2, 3, 3)) * 10
a

tensor([[[5.9445, 5.9636, 1.7486],
         [1.2101, 5.1058, 4.4432],
         [9.6727, 6.8322, 5.7573]],

        [[1.9854, 9.7991, 0.4793],
         [6.3677, 4.3852, 4.4977],
         [3.7931, 0.3165, 4.5605]]])

In [71]:
max_, indices = torch.max(a, dim=0, keepdims=True)
max_, indices

(tensor([[[5.9445, 9.7991, 1.7486],
          [6.3677, 5.1058, 4.4977],
          [9.6727, 6.8322, 5.7573]]]),
 tensor([[[0, 1, 0],
          [1, 0, 1],
          [0, 0, 0]]]))

In [79]:
torch.gather(a, 0, indices)

tensor([[[5.9445, 9.7991, 1.7486],
         [6.3677, 5.1058, 4.4977],
         [9.6727, 6.8322, 5.7573]]])

In [82]:
a = torch.rand((2, 3, 3))
a

tensor([[[0.5517, 0.5360, 0.4221],
         [0.7487, 0.9577, 0.5994],
         [0.3766, 0.7979, 0.8720]],

        [[0.4162, 0.5543, 0.0986],
         [0.9781, 0.2686, 0.3005],
         [0.9106, 0.8513, 0.6105]]])

In [88]:
a[]

tensor([[[0.4162, 0.5543, 0.0986],
         [0.9781, 0.2686, 0.3005],
         [0.9106, 0.8513, 0.6105]]])

In [80]:
input = torch.tensor([[1, 2, 3], [4, 5, 6]])
index = torch.tensor([[0, 2], [1, 0]])

output = torch.gather(input, 1, index)

In [76]:
output

tensor([[1, 3],
        [5, 4]])

In [90]:
a = torch.rand((2, 3, 3))
a

tensor([[[0.2519, 0.5664, 0.6653],
         [0.9189, 0.3980, 0.5378],
         [0.9487, 0.7584, 0.5255]],

        [[0.4926, 0.6816, 0.1492],
         [0.9710, 0.8404, 0.6978],
         [0.6151, 0.1344, 0.2134]]])

In [92]:
indices = torch.tensor([[0], [1]])
indices

tensor([[0],
        [1]])

In [96]:
# Select rows from tensor 'a' based on indices
output = a[torch.arange(a.size(0)).unsqueeze(1), indices]
output

tensor([[[[0.2519, 0.5664, 0.6653]],

         [[0.9189, 0.3980, 0.5378]]],


        [[[0.4926, 0.6816, 0.1492]],

         [[0.9710, 0.8404, 0.6978]]]])

In [103]:
output = a[[[0], [1]], [[0], [1]]]

output

tensor([[[0.2519, 0.5664, 0.6653]],

        [[0.9710, 0.8404, 0.6978]]])

In [95]:
output.shape

torch.Size([2, 1, 3])

In [97]:
torch.arange(a.size(0)).unsqueeze(1)

tensor([[0],
        [1]])

In [186]:
a = torch.tensor([[[1],
         [0],
         [0],
         [0]]])

In [187]:
a

tensor([[[1],
         [0],
         [0],
         [0]]])

In [188]:
a.shape

torch.Size([1, 4, 1])

In [199]:
mask = torch.zeros((2, 4, 2))

In [200]:
mask

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [201]:
mask = torch.scatter(mask, 2, a, 1)

In [202]:
mask = mask.to(torch.bool)

In [203]:
mask.shape

torch.Size([2, 4, 2])

In [204]:
mask

tensor([[[False,  True],
         [ True, False],
         [ True, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [False, False],
         [False, False]]])

In [207]:
t = torch.rand((2, 4, 2, 4))
t

tensor([[[[0.1417, 0.7151, 0.6690, 0.3251],
          [0.0235, 0.2930, 0.9365, 0.0396]],

         [[0.9811, 0.8005, 0.1042, 0.5879],
          [0.6985, 0.4576, 0.0693, 0.7841]],

         [[0.8053, 0.9804, 0.6434, 0.7365],
          [0.9275, 0.4729, 0.5870, 0.3247]],

         [[0.8115, 0.1752, 0.6965, 0.8973],
          [0.4066, 0.3148, 0.6798, 0.3301]]],


        [[[0.6101, 0.1328, 0.5040, 0.7107],
          [0.9991, 0.4564, 0.2482, 0.3644]],

         [[0.2259, 0.1610, 0.3701, 0.5265],
          [0.5559, 0.9668, 0.3575, 0.5897]],

         [[0.8984, 0.2974, 0.8993, 0.0938],
          [0.6954, 0.7260, 0.8383, 0.4805]],

         [[0.1635, 0.5466, 0.1174, 0.9500],
          [0.5112, 0.6315, 0.3939, 0.7213]]]])

In [209]:
t[[mask]]

TypeError: only integer tensors of a single element can be converted to an index

In [120]:
mask

tensor([0., 1., 0., 1., 0., 1., 0., 1.])

In [124]:
torch.rand(8)[mask.to(torch.bool)]

tensor([0.4276, 0.9118, 0.1684, 0.6855])

In [183]:
t = torch.tensor([[1, 2], [3, 4]])

In [185]:
t[[False, True]]

tensor([[3, 4]])

In [211]:
b = torch.rand((1, 2, 3))
b

tensor([[[0.9619, 0.4853, 0.0336],
         [0.3550, 0.6602, 0.9758]]])

In [212]:
mask = torch.tensor([
    [False, True]
])

In [213]:
b[mask]

tensor([[0.3550, 0.6602, 0.9758]])

In [215]:
b = torch.rand((1, 1, 2, 2))
b

tensor([[[[0.0240, 0.4572],
          [0.6506, 0.8826]]]])

In [216]:
mask = torch.tensor([])


In [219]:
a = torch.tensor([[1, 2], [3, 4]])
mask = torch.tensor([[True, False], [False, True]])
a[mask]

tensor([1, 4])